#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <termios.h>

#include <monocypher.h>

#define die(...) do { fprintf(stderr, __VA_ARGS__); exit(1); } while(0)

static
int
set_no_echo(struct termios *prev)
{
	struct termios term_noecho;
	if (tcgetattr(0, prev))
		return 1;
	term_noecho = *prev;
	term_noecho.c_lflag &= (tcflag_t)~ECHO;
	if (tcsetattr(0, TCSAFLUSH, &term_noecho))
		return 1;
	return 0;
}

static
uint32_t
read_password(uint8_t *buf, uint32_t bufsize)
{
	uint32_t password_size = 0;
	struct termios term_old;

	if (set_no_echo(&term_old)) {
		buf = fgets(buf, (int)bufsize, stdin);
	} else {
		fprintf(stderr, "Passphrase (Echo off): ");
		buf = fgets(buf, (int)bufsize, stdin);
		(void)tcsetattr(0, TCSAFLUSH, &term_old);
	}

	if (!buf)
		die("Failed to read password.\n");

	password_size = (uint32_t)strlen(buf);

	if (password_size + 1 == bufsize)
		die("Password was truncated.\n");

	if (password_size && buf[password_size - 1] == '\n')
		buf[password_size-- - 1] = '\0';

	if (!password_size)
		die("Password was empty.\n");

	return password_size;
}

int
main(void)
{
	uint8_t hash[32];
	uint32_t hash_size = 32;
	void *work_area = NULL;
	uint32_t nb_blocks = 512 * 1024;
	uint32_t nb_iterations = 1;
	uint8_t password[1024];
	uint32_t password_size = 0;
	uint8_t salt[16] = {
		/* Generated by fair dice roll. Guaranteed to be random. */
		0x77, 0xe4, 0xd7, 0x76, 0xc5, 0xe1, 0x0e, 0xd8,
		0x09, 0xfa, 0xb5, 0x74, 0xd6, 0x3c, 0xd4, 0xfc
	};
	uint32_t salt_size = 16;

	if (!(work_area = calloc(nb_blocks, 1024)))
		die("Failed to allocate work area.\n");

	password_size = read_password(password, sizeof(password));

	crypto_argon2i(
		hash, hash_size,
		work_area,
		nb_blocks, nb_iterations,
		password, password_size,
		salt, salt_size
	);

	printf("static const uint8_t public_key[%zu] = {\n", sizeof(hash));
	for (unsigned int i = 0; i < sizeof(hash); ++i) {
		if (i % 8 == 0)
			printf("\t");
		printf("0x%02x", hash[i]);
		if (i + 1 == sizeof(hash))
			printf("\n");
		else if (i % 8 == 7)
			printf(",\n");
		else
			printf(", ");
	}
	printf("};\n");

	return 0;
}
