#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <monocypher.h>

#define die(...) do { fprintf(stderr, __VA_ARGS__); exit(1); } while(0)

int
main(void)
{
	uint8_t hash[32];
	uint32_t hash_size = 32;
	void *work_area;
	uint32_t nb_blocks = 512 * 1024;
	uint32_t nb_iterations = 3;
	uint8_t password[1024];
	uint32_t password_size;
	uint8_t salt[16] = {
		/* Generated by fair dice roll. Guaranteed to be random. */
		0x77, 0xe4, 0xd7, 0x76, 0xc5, 0xe1, 0x0e, 0xd8,
		0x09, 0xfa, 0xb5, 0x74, 0xd6, 0x3c, 0xd4, 0xfc
	};
	uint32_t salt_size = 16;

	if (!(work_area = calloc(nb_blocks, 1024)))
		die("Failed to allocate work area.\n");

	if (!(fgets(password, sizeof(password), stdin)))
		die("Failed to read password.\n");

	password_size = (uint32_t)strlen(password);

	if (password_size + 1 == sizeof(password))
		die("Password was truncated.\n");

	if (password_size && password[password_size - 1] == '\n')
		password[password_size-- - 1] = '\0';

	if (!password_size)
		die("Password was empty.\n");

	crypto_argon2i(hash, hash_size, work_area, nb_blocks, nb_iterations, password, password_size, salt, salt_size);
	return 0;
}
